#include "core.h"

int main(){
    input inputList[] = {
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},        
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},                
        {{1, 2} , ADD},
        {{4, 1} , SUB},
        {{2, 5} , MUL},        
        {{2, 5} , DIV},        
    };
    int taskLen = sizeof(inputList)/sizeof(inputList[0]);
    queueTasks(inputList, taskLen);
    initTasks();    
    return 0;
}